spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_db?serverTimezone=UTC&useSSL=false
    username: root
    password: y000000
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false


server:
  port: 8081

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.milotnt.pojo